import { useEffect, useState } from "react";
import Head from "next/head";
import AppLayout from "../components/AppLayout";
import Button from "../components/Button";
import GitHub from "../components/Icons/Github";
import Logo from "../components/Icons/Logo";
import Avatar from "../components/Avatar";
import { colors } from "../styles/theme";

//  Firebase Client
import { loginWithGithub, authChange } from "/firebase/client.js";

export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    authChange(setUser(user));
  }, []);

  const handleClick = () => {
    loginWithGithub()
      .then((user) => {
        setUser(user);
        console.log(user);
      })
      .catch((err) => {
        console.log(err);
      });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AppLayout>
        <section>
          <Logo alt='logo' height={90} />
          <h1>Devter</h1>
          <h2>
            Talk about development <br></br>with developers
          </h2>
          <div>
            {user === null && (
              <Button onClick={handleClick}>
                <GitHub width={24} height={24} fill={"#fff"} />
                Login with Github
              </Button>
            )}

            {user && user.avatar && (
              <Avatar src={user.avatar} alt={user.name} text={user.name} />
            )}
          </div>
        </section>
      </AppLayout>

      <style jsx>{`
        img {
          height: 60px;
        }
        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }

        h1 {
          color: ${colors.primary};
          font-size: 2rem;
          margin-bottom: 0;
        }

        h2 {
          color: ${colors.secondary};
          font-size: 1.3rem;
          text-align: center;
        }

        .btn-container {
          margin-top: 0.3rem;
        }
      `}</style>
    </div>
  );
}
