import { useState } from 'react';
import Head from 'next/head';
import AppLayout from '../components/AppLayout';
import Button from '../components/Button';
import GitHub from '../components/Icons/Github';
import { fonts, colors } from '../styles/theme';

//Firebase Client
import app from '../firebase/client';
import { loginWithGithub } from '/firebase/client.js';


export default function Home() {

  const { user, setUser } = useState( null );

  const handleClick = () => {
    loginWithGithub().then( user => {
      const { avatar, username, url } = user;
      console.log( user );
    } ).catch( err => {
      console.log( err );
    } )
  }
  

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <img src="./images/twitter-logo.png" alt="Logo" />
          <h1>Devter</h1>
          <h2>Talk about development <br></br>with developers</h2>
          <div className='btn-container'>
            <Button onClick={handleClick}>
              <GitHub width={24} height={24} fill={'#fff'} />
              Login with Github
            </Button>
          </div>
        </section>
      </AppLayout>


      <style jsx>{`
      img {
        height: 60px;
      }

      section {
        display: grid;
        height: 100%;
        place-content: center;
        place-items: center;
      }

      h1 {
        color: ${colors.primary};
        font-size: 2rem;
        margin-bottom: 0;
      }

      h2 {
        color: ${colors.secondary};
        font-size: 1.3rem;
        text-align:center;
      }

      .btn-container {
        margin-top: .3rem;
      }
      
      `}</style>
      

    </div>
  )
}
